### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by christian-ortmann** [INFO-526-S24/project-01-Plotcrafters#1]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

Sachin Patil - @sachinpatil3115

Cristian ortmann -@christian-ortmann

Abhishek Kumar - @Abhi291712

Tejas Bhawari - @tezz-us

Nick Ferrante - @n-ferrante

Monika Tejaswi - @KommareddyMonicaTejaswi

- Describe the goal of the project.
Understand patterns, trends, and insights regarding UFO activities around the world based on location and time.

- Describe the data used or collected.
The data is from the National UFO Recording center and dates back to 1949. The dataset contains variables such as location, time, and UFO shape, among other variables.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
They plan to do a global and temporal distribution analysis. They intend to find conclusions that explain areas with high UFO activity and also determine patterns in timing and duration of UFO sightings.

- Is there anything that is unclear from the proposal?
They don't include what type of plots they intend to use to display and understand the data. 

- Provide constructive feedback on how the team might be able to improve their project.
Their analysis is a bit sparse, they don't explain what they mean by investigating for trends. What statistical methods do they intend to use to analyze any trends.  Include what plots they intend to use.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
Correlating population density to the amount of sightings.

- Provide constructive feedback on any issues with file and/or code organization.
Too much code in the proposal, should have suppressed it. Would make it difficult for a non-technical person to understand. We like that they include summary statistics though.

**Comment by AjaykATgitHub** [comment]
Thank you for your constructive feedback. We appreciate your insights and are committed to addressing the areas where clarity and improvement are needed in our project proposal:

1. Clarity on Plots and Visualization:

As we delve into the project and work with the data, we understand the importance of providing specific details on the types of plots and visualizations. Our approach will evolve based on the dataset, and we will ensure to include a dynamic section that outlines the visual tools we intend to use. This will offer a clearer understanding of how we plan to represent and interpret the evolving data.
2. Detailed Explanation of "Investigating Trends":

To provide a more comprehensive view, we will offer a detailed breakdown of the statistical methods we plan to employ as we progress through the analysis. This will include information on the evolving statistical techniques, measures, and analyses used to identify and interpret trends within the dataset.
3. Inclusion of Specific Plots:

As we navigate the data, we recognize the need for explicit details on the specific plots we intend to utilize. While our initial proposal outlines a general approach, we will adapt and incorporate visualizations that best align with the evolving data and research questions. This flexibility will allow us to tailor our visualizations to the nuances of the dataset.
4. Highlighting Correlation with Population Density:

Your interest in correlating population density with UFO sightings is duly noted. We will emphasize this correlation in our presentation, dedicating a section to exploring and highlighting any relationships between population density and the frequency of UFO sightings. The specifics of this correlation will become clearer as we progress with the analysis.
5. Opportunity for Further Suggestions:

As we embark on the project, we invite ongoing feedback and additional suggestions. Understanding that the analysis will evolve based on the data, your input is crucial, and we want to ensure that our investigations align with your expectations and add value to the project.
We look forward to the collaborative exploration of the dataset and the iterative refinement of our analysis.
