### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by AgastyaDeshraju** [INFO-526-S24/project-01-Plotcrafters#2]
The following is the peer review of the project proposal by "fight club". The team members that participated in this review are 

- Agastya Deshraju - @AgastyaDeshraju 
- Usama Ahmed - @usamaahmedsh
- Naitik Shah - @naitik2608
- Gorantla Sai Laasya - @Sailaasya-1
- Lakshmi Anchula - @lakshmineharika
- Divya Dhole - @Divyadhole

- **Describe the goal of the project.**
The purpose of this project is to use temporal, geographical, and descriptive data analysis to unravel the mystery surrounding UFO encounters. They intend to answer the questions: 1) The geographic distribution of the sightings, and 2) Trends in the time of day with respect to the sightings.

- **Describe the data used or collected.**
The National UFO Reporting Center (NUFORC) is the source of the dataset, which includes over 80,000 records of UFO sightings since 1949. It provides a solid foundation for thorough study since it contains vital information like latitude and longitude for geographic analysis, date and time stamps for temporal analysis, and thorough descriptions of each sighting. This large dataset makes it possible to do a thorough analysis of the trends in UFO sightings around the world.

- **Describe how the research question will be answered, e.g. what approaches / methods will be used.**
They have broadly mentioned that they will use time, location (latitude, longitude), and state data for the visualizations but they have not mentioned any specific methods or approaches that they will use for the first questions. For the second question, they’ve mentioned using bins to aggregate the data into different times of day and then further analyze the sighting patterns using these bins. 

- **Is there anything that is unclear from the proposal?**
It would be good if they have included the type of plot they are using for visualization and a little more clarity on the other variables. The methodology and the results are the main factors in their decision to select one dataset above others, not the other way around. Why did they choose to take the dataset?

- **Provide constructive feedback on how the team might be able to improve their project.**
They can improve their analysis by segmenting the latitude and longitude by key areas e.g. sightings near Area 51. That will provide us with more insight. Improvement can be also be made by giving more clarity their approach

- **What aspect of this project are you most interested in and would like to see highlighted in the presentation.**
The temporal trends study is very interesting, especially if it can link sightings to certain events, seasons, or changes across several decades. Emphasizing any noteworthy trends or aberrations in the dates of sightings may provide intriguing insights into possible behavior of extraterrestrials or cultural reporting patterns.

- **Provide constructive feedback on any issues with file and/or code organization.**
The team could benefit greatly from having consistent documentation, clear naming conventions and organizing the code chunks smoothly for different analysis stages, which would improve readability and comprehension for the general audience.

**Comment by AjaykATgitHub** [comment]
**Dataset Selection Rationale:**

Our decision to choose the UFO sightings dataset from [NUFORC](http://www.nuforc.org/) was primarily driven by the dataset's comprehensive nature, spanning over 80,000 records dating back to 1949. The dataset offers a unique opportunity to explore the temporal and spatial patterns of UFO activities globally. Key considerations in our dataset selection include:

1. **Rich Information:**

The dataset provides detailed information, including latitude, longitude, date and time stamps, and descriptions of each UFO sighting. This richness allows for a thorough analysis of both spatial and temporal aspects.

2. **Temporal Range:**

The extensive temporal range of the dataset enables us to investigate how UFO sightings have evolved over the decades, identifying potential trends and patterns.

2. **Global Scope:**

With sightings recorded globally, the dataset allows for a comprehensive exploration of UFO activity in different regions, aiding in the identification of geographical hotspots.

**Methodology:**

Our methodology involves employing specific visualizations and analyses to derive meaningful insights from the dataset:

- Global Distribution Analysis:

Utilizing latitude, longitude, and State data, we plan to visualize the global distribution of UFO sightings. Specific plot types will be employed to enhance the clarity of our findings.

- Temporal Trends by Time of Day:

We will examine temporal trends by creating time bins (e.g., morning, afternoon, evening, night) using the time data from the dataset. This will enable us to identify patterns associated with different times of the day.

 Here are the adjustments we plan to implement:

- Segmentation of Latitude and Longitude:

We acknowledge the importance of segmenting the latitude and longitude data to focus on key areas of interest, such as sightings near Area 51.
Plan: We will incorporate a specific segmentation approach to identify and analyze sightings in key regions, including but not limited to Area 51. This segmentation will allow us to delve deeper into specific geographic locations and uncover patterns unique to those areas.

- Clarity in Approach:

Recognizing the need for more clarity in our approach, we aim to provide a detailed outline of our analysis steps, ensuring transparency in our methodology.
Plan: We will explicitly outline the steps involved in our analysis, including data preprocessing, segmentation, and the rationale behind our visualization choices. This will provide a clear roadmap for understanding our approach.
- Additional Insights:

To further enrich our analysis, we will explore additional avenues for gaining insights. This may involve investigating correlations with external factors or exploring trends related to specific time periods.
We are committed to implementing these enhancements and believe they will contribute to a more thorough and insightful analysis. Your feedback is invaluable, and we look forward to presenting an improved and refined exploration of the UFO sightings dataset.

**Comment by AjaykATgitHub** [comment]
Thank you for your constructive feedback, and we have addressed the issues raised in this feedback, hence closing this thread.
