### ISSUE TITLE
Proposal feedback

### ISSUE THREAD

**Issue by Gchism94** [INFO-526-S24/project-01-Plotcrafters#3]
Dear TEAM_NAME: Below is the score breakdown for your proposal. Details of things that should be updated/revised are provided in separate issues. As you address them, you should close the individual issues.

You can do this in one of two ways:

- On GitHub, by clicking on Close issue
- Via a commit that directly addresses the issue.

Please use the second method wherever a fix can be tied to a commit. If you preface your commit messages with "Fixes", "Fixed", "Fix", "Closed", or "Close", the issue will be closed when you push the changes to your repo. For example, suppose you want to close issue `#2` which, hypothetically, suggested that you add a new line to the README, your commit message can say something like `Add a new line to the README, closes #2`.

Once you've closed all of the other issues, close this one as well, so that going into the presentation you have no open issues remaining.

|          | Available | Earned |
|----------|-----------|--------|
| Data     | 3         |     2.5   |
| Proposal | 5         |    2    |
| Workflow | 1         |     0   |
| Teamwork | 1         |   1     |
| Total    | 10        |     5.5   |

**Feedback**:
Data: Good work using a `glimpse()`, but summary is not the best to show aspects of the columns. Use the `dlookr` package for this. 
Workflow: Your workflow is too vague, making it unclear how the project will be completed. 

**Overall**:
I'm honestly a little surprised that your feedback to the peer-reviews contained more information than the actual proposal. This shows that you addressed the feedback but did not implement it comprehensively in the proposal. That being said, the responses were also too vague in a few critical areas: 
1. How are you going to wrangle the data from the original columns to the end plots/analyses. 
2. What are the actual plots you will be using, you need 2/ question, I don't see any specifically named. 
3. The plan itself is more of a statement of what you will do, but you need to be more step-by-step. 
4. I would have liked to see a timeline of some kind to help me see how feasible the project is in scope.

**Comment by Gchism94** [comment]
If you would like a regrade, please address and resubmit your proposal by **Monday, Feb 19th, 11:59pm**.

**Procedure**

1. Close this issue.
2. Open a new blank one requesting a regrade

Your final score will be the midpoint between the two scores.

**Comment by ustusharkant** [comment]
Hello Professor,

Thank you so much for the valuable feedback. We have incorporated all the changes in our proposal.qmd file and upon publishing  the github pages we are closing the issue. 

Request you to kindly take a look a regrade our effort.

Thanks
